/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class li_winston_dpdktest_MTCP */

#ifndef _Included_li_winston_dpdktest_MTCP
#define _Included_li_winston_dpdktest_MTCP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1destroy
  (JNIEnv *, jclass);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_getconf
 * Signature: (Lli/winston/dpdktest/MtcpConf;)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1getconf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_setconf
 * Signature: (Lli/winston/dpdktest/MtcpConf;)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1setconf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_core_affinitize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1core_1affinitize
  (JNIEnv *, jclass, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_create_context
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1create_1context
  (JNIEnv *, jclass, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_destroy_context
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1destroy_1context
  (JNIEnv *, jclass, jlong);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_register_signal
 * Signature: (ILli/winston/dpdktest/MtcpSighandler;)Lli/winston/dpdktest/MtcpSighandler;
 */
JNIEXPORT jobject JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1register_1signal
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_pipe
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1pipe
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_getsockopt
 * Signature: (JIII[I)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1getsockopt
  (JNIEnv *, jclass, jlong, jint, jint, jint, jintArray);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_setsockopt
 * Signature: (Lli/winston/dpdktest/MtcpConf;III[I)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1setsockopt
  (JNIEnv *, jclass, jobject, jint, jint, jint, jintArray);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_setsock_nonblock
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1setsock_1nonblock
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_socket_ioctl
 * Signature: (JII[I)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1socket_1ioctl
  (JNIEnv *, jclass, jlong, jint, jint, jintArray);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_socket
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1socket
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_bind
 * Signature: (JILli/winston/dpdktest/SockaddrIn;)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1bind
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_listen
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1listen
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_accept
 * Signature: (JILli/winston/dpdktest/SockaddrIn;)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1accept
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_init_rss
 * Signature: (JLjava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1init_1rss
  (JNIEnv *, jclass, jlong, jstring, jint, jstring, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_connect
 * Signature: (JILli/winston/dpdktest/SockaddrIn;)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1connect
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_close
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1close
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_abort
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1abort
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_read
 * Signature: (JI[B)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1read
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_readv
 * Signature: (JI[[B)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1readv
  (JNIEnv *, jclass, jlong, jint, jobjectArray);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_write
 * Signature: (JILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1write
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_writev
 * Signature: (JI[[B)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1writev
  (JNIEnv *, jclass, jlong, jint, jobjectArray);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_epoll_create
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1epoll_1create
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_epoll_ctl
 * Signature: (JIIIIJ)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1epoll_1ctl
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    mtcp_epoll_wait
 * Signature: (JILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_mtcp_1epoll_1wait
  (JNIEnv *, jclass, jlong, jint, jobject, jint);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_li_winston_dpdktest_MTCP_errno
  (JNIEnv *, jclass);

/*
 * Class:     li_winston_dpdktest_MTCP
 * Method:    set_errno
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_li_winston_dpdktest_MTCP_set_1errno
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
