/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class li_winston_dpdktest_Epwget */

#ifndef _Included_li_winston_dpdktest_Epwget
#define _Included_li_winston_dpdktest_Epwget
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     li_winston_dpdktest_Epwget
 * Method:    doWget
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_li_winston_dpdktest_Epwget_doWget
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
